Cluster Creation with Group RBAC -add optional GDCc 1.10 field for supporting group RBAC enabled clusters -add function evaluating GDCc version number being used to determine version dependant logic

diff --git a/bootstrap/create-cluster.yaml b/bootstrap/create-cluster.yaml
--- a/bootstrap/create-cluster.yaml
+++ b/bootstrap/create-cluster.yaml
@@ -164,6 +164,45 @@ steps:
       echo "$output"
     }
 
+    # Use this function to determine if the required version is met. 
+    # Return true if met. Return false if not met. 
+    # This can be used when version checking is important.
+    function gdc_version_evaluate() {
+      current_version="$1"
+      required_version="$2"
+
+      regex='^([0-9]+(\.[0-9]+)*)'
+
+      if [[ "$current_version" =~ $regex ]]; then
+          current_numeric="${BASH_REMATCH[1]}"
+      else
+          echo "Error Could not extract numeric part from current version: '$current_version'. Should be in the format X.Y.X, like 1.8.0." >&2
+          return 1
+      fi
+
+      if [[ "$required_version" =~ $regex ]]; then
+          target_numeric="${BASH_REMATCH[1]}"
+      else
+          echo "Error Could not extract numeric part from target version: '$required_version'. Should be in the format X.Y.X, like 1.8.0." >&2
+          return 1 
+      fi
+
+      if [[ "$current_numeric" == "$target_numeric" ]]; then
+          return 0 # Versions are equal
+      fi
+
+      first_sorted_version=$(printf "%s\n%s\n" "$current_numeric" "$target_numeric" | sort -V | head -n1)
+
+
+      if [[ "$first_sorted_version" == "$target_numeric" ]]; then 
+          # current_version < required_version
+          return  0
+      else
+          # required_version > current_version
+          return 1
+      fi
+    }
+
     [[ -z "${STORE_ID}" ]] && die "STORE_ID not set"
 
     NODE_LOCATION=${ZONE}
@@ -236,26 +275,44 @@ steps:
     if [ $? -eq 0 ]; then
       log_build_step "Cluster already created, skipping to next step."
     else
-      log_build_step "Creating cluster"
-
       # Create a new FD to support stdout,stderr to console + saving to bash variable
       # This is used to output the opid before the operation has completed
       exec 5>&1
 
-      out=$(
-        gcloud edge-cloud container clusters create $CLUSTER_NAME \
-          --control-plane-node-location=$NODE_LOCATION \
-          --control-plane-node-count=$NODE_COUNT \
-          --cluster-ipv4-cidr=$CLUSTER_IPV4_CIDR \
-          --services-ipv4-cidr=$SERVICES_IPV4_CIDR \
-          --external-lb-ipv4-address-pools=$EXTERNAL_LOAD_BALANCER_IPV4_ADDRESS_POOLS \
-          --control-plane-shared-deployment-policy=ALLOWED \
-          --location=$LOCATION \
-          --project=$FLEET_PROJECT_ID \
-          --release-channel=NONE \
-          --version $CLUSTER_VERSION \
-          --offline-reboot-ttl=7d 2>&1 | tee /dev/fd/5
-      )
+      if [[ "${SKIP_IDENTITY_SERVICE}" == "FALSE" ]] && gdc_version_evaluate "${CLUSTER_VERSION}" "1.10.0"; then
+      log_build_step "Creating cluster with Group RBAC"
+        out=$(
+          gcloud alpha edge-cloud container clusters create $CLUSTER_NAME \
+            --control-plane-node-location=$NODE_LOCATION \
+            --control-plane-node-count=$NODE_COUNT \
+            --cluster-ipv4-cidr=$CLUSTER_IPV4_CIDR \
+            --services-ipv4-cidr=$SERVICES_IPV4_CIDR \
+            --external-lb-ipv4-address-pools=$EXTERNAL_LOAD_BALANCER_IPV4_ADDRESS_POOLS \
+            --control-plane-shared-deployment-policy=ALLOWED \
+            --location=$LOCATION \
+            --project=$FLEET_PROJECT_ID \
+            --release-channel=NONE \
+            --version $CLUSTER_VERSION \
+            --offline-reboot-ttl=7d \
+            --enable-google-group-authentication 2>&1 | tee /dev/fd/5
+          )
+      else
+        log_build_step "Creating cluster"
+        out=$(
+            gcloud edge-cloud container clusters create $CLUSTER_NAME \
+              --control-plane-node-location=$NODE_LOCATION \
+              --control-plane-node-count=$NODE_COUNT \
+              --cluster-ipv4-cidr=$CLUSTER_IPV4_CIDR \
+              --services-ipv4-cidr=$SERVICES_IPV4_CIDR \
+              --external-lb-ipv4-address-pools=$EXTERNAL_LOAD_BALANCER_IPV4_ADDRESS_POOLS \
+              --control-plane-shared-deployment-policy=ALLOWED \
+              --location=$LOCATION \
+              --project=$FLEET_PROJECT_ID \
+              --release-channel=NONE \
+              --version $CLUSTER_VERSION \
+              --offline-reboot-ttl=7d 2>&1 | tee /dev/fd/5
+            )
+      fi
 
       [[ $? -ne 0 ]] && die "Failure from gcloud edge-cloud container clusters" "$out"
 
@@ -338,7 +395,8 @@ steps:
     gcloud beta container fleet config-management apply --membership=$CLUSTER_NAME \
         --config=./apply-spec.yaml --project $FLEET_PROJECT_ID
 
-    if [[ "${SKIP_IDENTITY_SERVICE}" == "FALSE" ]]; then
+    # Apply old Group RBAC steps cluster version is less than 1.10.0
+    if [[ "${SKIP_IDENTITY_SERVICE}" == "FALSE" ]] &&  ! gdc_version_evaluate "${CLUSTER_VERSION}" "1.10.0"; then
       log_build_step "Configuring Group RBAC"
       FLEET_PROJECT_NUMBER=$(gcloud projects describe $FLEET_PROJECT_ID --format='value(projectNumber)')
       kubectl patch clientconfig default -n kube-public --type=merge -p '{"spec":{"authentication":[{"google":{"audiences":["//'${GKEHUB_API_ENDPOINT}'/projects/'${FLEET_PROJECT_NUMBER}'/locations/global/memberships/'${CLUSTER_NAME}'"]},"name":"google-authentication-method"}]}}'
