Increase platform healthcheck timeout from 1h to 2h per b/506224078

diff --git a/module/create-cluster.yaml b/module/create-cluster.yaml
--- a/module/create-cluster.yaml
+++ b/module/create-cluster.yaml
@@ -497,15 +497,15 @@ steps:
       [[ ${count} -ge ${max_retries_for_healthcheck_creation} ]] && die "Health check resource not created after 20min"
 
       log_build_step "Waiting for platform healthchecks to pass"
-      if ! kubectl wait healthchecks.validator.gdc.gke.io/default --for condition=PlatformHealthy --timeout=1h; then
+      if ! kubectl wait healthchecks.validator.gdc.gke.io/default --for condition=PlatformHealthy --timeout=2h; then
         kubectl describe healthchecks.validator.gdc.gke.io/default
-        die "Platform is not healthy after 1h. Please review the failed platform health checks."
+        die "Platform is not healthy after 2h. Please review the failed platform health checks."
       fi
 
       # Calculate workload timeout by removing non-workload related buffer time from the over build timeout.
-      # ($TIMEOUT_IN_SECONDS) - (1h for platform health) - (1h for cluster health)
+      # ($TIMEOUT_IN_SECONDS) - (2h for platform health) - (1h for cluster health)
       #                       - (10m for extra buffer) - (30m for vm wait)
-      WORKLOAD_TIMEOUT="$(($TIMEOUT_IN_SECONDS-"9600"))"
+      WORKLOAD_TIMEOUT="$(($TIMEOUT_IN_SECONDS-"13200"))"
 
       log_build_step "Waiting for workload healthchecks to pass"
       if ! kubectl wait healthchecks.validator.gdc.gke.io/default --for condition=WorkloadsHealthy --timeout="${WORKLOAD_TIMEOUT}s"; then
