feat: Support enable robin cns for cluster creation and update

diff --git a/module/modify-cluster.yaml b/module/modify-cluster.yaml
--- a/module/modify-cluster.yaml
+++ b/module/modify-cluster.yaml
@@ -52,6 +52,45 @@ steps:
       echo "$output"
     }
 
+    # Use this function to determine if the required version is met. 
+    # Return true if met. Return false if not met. 
+    # This can be used when version checking is important.
+    function gdc_version_evaluate() {
+      current_version="$1"
+      required_version="$2"
+
+      regex='^([0-9]+(\.[0-9]+)*)'
+
+      if [[ "$current_version" =~ $regex ]]; then
+          current_numeric="${BASH_REMATCH[1]}"
+      else
+          echo "Error Could not extract numeric part from current version: '$current_version'. Should be in the format X.Y.X, like 1.8.0." >&2
+          return 1
+      fi
+
+      if [[ "$required_version" =~ $regex ]]; then
+          required_numeric="${BASH_REMATCH[1]}"
+      else
+          echo "Error Could not extract numeric part from target version: '$required_version'. Should be in the format X.Y.X, like 1.8.0." >&2
+          return 1 
+      fi
+
+      if [[ "$current_numeric" == "$required_numeric" ]]; then
+          return 0 # Versions are equal
+      fi
+
+      first_sorted_version=$(printf "%s\n%s\n" "$current_numeric" "$required_numeric" | sort -V | head -n1)
+
+
+      if [[ "$first_sorted_version" == "$required_numeric" ]]; then 
+          # current_version > required_version
+          return  0
+      else
+          # current_version < required_version
+          return 1
+      fi
+    }
+
     [[ -z "${STORE_ID}" ]] && die "STORE_ID not set"
 
     NODE_LOCATION=${ZONE}
@@ -84,6 +123,7 @@ steps:
     export MAINTENANCE_WINDOW_RECURRENCE=$(parse_csv_optional "$CLUSTER_INTENT" "maintenance_window_recurrence")
     export SUBNET_VLANS=$(parse_csv_optional "$CLUSTER_INTENT" "subnet_vlans")
     export LABELS=$(parse_csv_optional "$CLUSTER_INTENT" "labels")
+    export CLUSTER_VERSION=$(parse_csv_required "$CLUSTER_INTENT" "cluster_version")
 
     export MAINTENANCE_EXCLUSION_NAMES=$(echo "$CLUSTER_INTENT" | head -n1 | tr , '\n' | tr -d '"' | sort -n | grep 'maintenance_exclusion_name.*')
     export MAINTENANCE_EXCLUSION_STARTS=$(echo "$CLUSTER_INTENT" | head -n1 | tr , '\n' |  tr -d '"' | sort -n | grep 'maintenance_exclusion_start.*')
@@ -202,6 +242,15 @@ steps:
       fi
     done
 
+    ROBIN_CNS_ARG=""
+    if [[ "${ENABLE_ROBIN_CNS}" == "TRUE" ]] && gdc_version_evaluate "${CLUSTER_VERSION}" "1.12.0"; then
+      echo "Enabling Robin CNS"
+      gcloud edge-cloud container clusters update $CLUSTER_NAME \
+        --project=$FLEET_PROJECT_ID \
+        --location=$LOCATION \
+        --enable-robin-cns
+    fi
+
     echo "Cluster Modify Succeeded: $CLUSTER_NAME"
 
   env:
@@ -217,6 +266,7 @@ steps:
   - 'GIT_SECRETS_PROJECT_ID=$_GIT_SECRETS_PROJECT_ID'
   - 'STORE_ID=$_STORE_ID'
   - 'ZONE=$_ZONE'
+  - 'ENABLE_ROBIN_CNS=$_ENABLE_ROBIN_CNS'
 
 timeout: 600s
 options:
